// flow-typed signature: a8e34d613740d11bdd184d7ad8835634
// flow-typed version: <<STUB>>/thunk_v^0.0.1/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'thunk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'thunk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'thunk/lib/thunk' {
  declare module.exports: any;
}

declare module 'thunk/test/thunk.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'thunk/index' {
  declare module.exports: $Exports<'thunk'>;
}
declare module 'thunk/index.js' {
  declare module.exports: $Exports<'thunk'>;
}
declare module 'thunk/lib/thunk.js' {
  declare module.exports: $Exports<'thunk/lib/thunk'>;
}
declare module 'thunk/test/thunk.test.js' {
  declare module.exports: $Exports<'thunk/test/thunk.test'>;
}
